MyMentor/urls.py
from django.urls import path
from . import views as mentorViews
urlpatterns = [
    path('login/', mentorViews.mentor_login, name='mentorLogin'),
    path('logout/', mentorViews.mentor_logout, name='mentorLogout'),
    path('home/', mentorViews.mentor_home, name='mentorHome'),
    path('notify-students/', mentorViews.notify_student, name='NotifyStudent'),
    path('studentregistrations/', mentorViews.register_student, name='registerStudent'),
    path('enter-student-marks-mid1/', mentorViews.enter_mid1, name='StudentMid1'),
    path('enter-student-marks-mid2/', mentorViews.enter_mid2, name='StudentMid2'),
    path('enter-student-marks-sem1/', mentorViews.enter_sem1, name='StudentSem1'),
    path('enter-student-attendance/', mentorViews.student_monthly_attendance, name='Attendance'),
]

MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as ProjectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProjectView.index, name='HomePage'),
    path('mentor/', include('MyMentor.urls')),
    path('student/', include('MyStudent.urls')),
]

MyMentor/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Mentor(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    mentorname = models.CharField(max_length=128)
    mentordesignation = models.CharField(max_length=256)


    def __str__(self):
        return self.mentorname


class NotifyStudents(models.Model):
    mentorname = models.ForeignKey(Mentor, on_delete=models.CASCADE)
    message = models.CharField(max_length=256)
    datetime = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.mentorname)

MyStudent/models.py
from django.db import models
from MyMentor.models import Mentor
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.

class Student(models.Model):
    username = models.ManyToManyField(User)
    studentid = models.CharField(max_length=10, unique=True, primary_key=True)
    name = models.CharField(max_length=128)
    sem = models.IntegerField()
    branch = models.CharField(max_length=128)
    batch = models.IntegerField()
    regulation = models.CharField(max_length=32)
    mentorname = models.CharField(max_length=64)

    def __str__(self):
        return str(self.studentid)

    def get_studentid(self):
        return str(self.studentid)


class StudentMarkMid1(models.Model):
    studentid = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject0 = models.IntegerField()
    subject1 = models.IntegerField()
    subject2 = models.IntegerField()
    subject3 = models.IntegerField()
    subject4 = models.IntegerField()
    subject5 = models.IntegerField()
    subject6 = models.IntegerField()
    lab0 = models.IntegerField()
    lab1 = models.IntegerField()


    def __str__(self):
        return str(self.studentid)



class StudentMarkMid2(models.Model):
    studentid = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject0 = models.IntegerField()
    subject1 = models.IntegerField()
    subject2 = models.IntegerField()
    subject3 = models.IntegerField()
    subject4 = models.IntegerField()
    subject5 = models.IntegerField()
    subject6 = models.IntegerField()
    lab0 = models.IntegerField()
    lab1 = models.IntegerField()


    def __str__(self):
        return str(self.studentid)


class StudentMarkSem1(models.Model):
    studentid = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject0 = models.IntegerField()
    subject1 = models.IntegerField()
    subject2 = models.IntegerField()
    subject3 = models.IntegerField()
    subject4 = models.IntegerField()
    subject5 = models.IntegerField()
    subject6 = models.IntegerField()
    lab0 = models.IntegerField()
    lab1 = models.IntegerField()
    sgpa = models.FloatField()
    cgpa = models.FloatField()

    def __str__(self):
        return str(self.studentid)


class StudentMonthlyAttendance(models.Model):
    studentid = models.ForeignKey(Student, on_delete=models.CASCADE)
    datetime = models.DateTimeField(default=timezone.now)
    percentage = models.FloatField()

MyMentor/forms.py
from django import forms

MyMentor/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

# Packages For Mentor Login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

#
from MyStudent.models import Student, StudentMonthlyAttendance
from .models import Mentor, NotifyStudents


# Student Forms
from MyStudent.forms import StudentForm, StudentMarkMid1Form, StudentMarkMid2Form,\
    StudentMarkSem1Form, StudentMonthlyAttendanceForm

# Create your Mentor views here.


# For login view
def mentor_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        request.session['presentuser'] = username
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active and user.is_staff:
                request.session['isMentor'] = True
                login(request, user)
                return HttpResponseRedirect(reverse('mentorHome'))
            else:
                return HttpResponse("YOU ARE NOT A STAFF MEMBER. <a href='/'>Go Home</a>")
        else:
            print("Student Tried to login or login failed")
            print("username {} and password {}".format(username, password))
            return HttpResponse("INVALID DETAILS <a href='/'>Go Home</a>")
    else:
        return render(request, 'myMentor/login.html')


@login_required
def mentor_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('HomePage'))


# Consists CRUD student, students marks, student attendance, notifications.
@login_required
def mentor_home(request):
    if request.session.get('isMentor'):
        username = request.session.get('presentuser')
        # Get Mentor ID to Get Mentor UserName
        mentorUser = User.objects.filter(username=username).values('id')
        mentorUserDict = mentorUser[0]
        mentorid = mentorUserDict['id']

        # Get MentorName to get the students under Mentor
        mentor = Mentor.objects.filter(username=mentorid).values('mentorname')
#         print(mentor)
        mentorDict = mentor[0]
        mentorname = mentorDict['mentorname']
#         print(mentorname)
        request.session['mentorname'] = mentorname
#         print(request.session.get('mentorname'))
        # Get Students by using mentorName

        students = Student.objects.filter(mentorname=mentorname)

        # students = Student.objects.filter(mentorname=mentor)
        return render(request, 'myMentor/home.html', {'students': students})
    else:
        return HttpResponse("404 Page not found.")


@login_required
def register_student(request):
    if request.session.get('isMentor'):
        if request.method == 'POST':
            form = StudentForm(request.POST)
            if form.is_valid():
                # Create account for students
                student_username = request.POST.get('studentid')
                # print(student_username)
                User.objects.create_user(username=student_username, password='tkrcet@123')
                form.save(commit=False)
                form.username = request.user
                form.save()
                return HttpResponseRedirect(reverse('registerStudent'))
        else:
            form = StudentForm()
            return render(request, 'myMentor/studentreg.html', {'form': form, 'mentorname': request.session.get('mentorname')})
    else:
        return HttpResponse("404 page not found.")


@login_required
def enter_mid1(request):
    if request.session.get('isMentor'):
        if request.method == 'POST':
            form = StudentMarkMid1Form(request.POST)
            form.save()
            return HttpResponseRedirect(reverse('StudentMid1'))
        else:
            form = StudentMarkMid1Form()
            return render(request, 'myMentor/marksdetails.html', {'form': form, 'value': 1})
    else:
        return HttpResponse("404 Page not found.")
    
    
@login_required
def enter_mid2(request):
    if request.session.get('isMentor'):
        if request.method == 'POST':
            form = StudentMarkMid2Form(request.POST)
            form.save()
            return HttpResponseRedirect(reverse('StudentMid2'))
        else:
            form = StudentMarkMid2Form()
            return render(request, 'myMentor/marksdetails.html', {'form': form, 'value': 2})
    else:
        return HttpResponse("404 page not found.")
    
    
@login_required
def enter_sem1(request):
    if request.session.get('isMentor'):
        if request.method == 'POST':
            form = StudentMarkSem1Form(request.POST)
            form.save()
            return HttpResponseRedirect(reverse('StudentSem1'))
        else:
            form = StudentMarkSem1Form()
            return render(request, 'myMentor/marksdetails.html', {'form': form, 'value': 3})
    else:
        return HttpResponse("404 page not found.")


@login_required
def notify_student(request):
    if request.session.get('isMentor'):
        if request.method == 'POST':
            message = request.POST.get('message')
            MentorUSer = User.objects.get(username=request.session.get('presentuser'))
            id = Mentor.objects.get(username=MentorUSer.id)
            # print(id.id)
            NotifyStudents.objects.create(mentorname=id, message=message)
            return HttpResponseRedirect(reverse('NotifyStudent'))
        else:
            MentorUSer = User.objects.get(username=request.session.get('presentuser'))
            id = Mentor.objects.get(username=MentorUSer.id)
            notifications = NotifyStudents.objects.all().filter(mentorname=id).order_by('-datetime')
#             print(notifications)
            return render(request, 'myMentor/notifystudents.html', {'notifications': notifications})
    else:
        return HttpResponse("404 page not found.")


@login_required
def student_monthly_attendance(request):
    if request.session.get('isMentor'):
        if request.method == 'POST':
            form = StudentMonthlyAttendanceForm(request.POST)
            form.save()
            return HttpResponseRedirect(reverse('Attendance'))
        else:
            form = StudentMonthlyAttendanceForm()
            return render(request, 'myMentor/marksdetails.html', {'form': form, 'value': 4})
    else:
        return HttpResponse("404 page not found.")

templates/myMentor/home.html
{% extends 'myMentor/mentorBase.html' %}
{% load static %}
{% block title %}
    Mentor Home
{% endblock %}
{% block mentorcontent %}
<center><h4>Your Student Details</h4></center>
<table class="table table-bordered">
                          <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Sem</th>
                                <th scope="col">branch</th>
                                <th scope="col">batch</th>
                                <th scope="col">Regulation</th>
                            </tr>
                            <tbody>
                                {% for student in students %}
                                    <tr>
                                        <td>{{ student.studentid }}</td>
                                        <td>{{ student.name }}</td>
                                        <td>{{ student.sem }}</td>
                                        <td>{{ student.branch }}</td>
                                        <td>{{ student.batch }}</td>
                                        <td>{{ student.regulation }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                          </thead>
                        </table>
{% endblock %}

templates/myMentor/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Mentor-Login @College
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'signin.css' %}">

{% endblock %}
{% block content %}
<div class="container-fluid rounded shadow-lg p-4" style="width: 80%; height: auto">
    <img class="mb-4 border-top" src="{% static 'images/college-logo.png' %}" alt="college-logo" width=100% height=auto>
    <h2><center>Mentor Login</center></h2>
    <hr>
    <form method="POST">
        {% csrf_token %}
          <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="username" aria-describedby="emailHelp">
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="password">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <div class="pt-3">
        <small class="text-muted">
            Go back?<a style="color: green" href="{%url 'HomePage' %}">&nbsp;Home</a>
        </small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
    <hr>
</div>

{% endblock %}

templates/myMentor/marksdetails.html
{% extends 'myMentor/mentorBase.html' %}
{% load static %}
{% block title %}
    Enter_Details
{% endblock %}
{% block mentorcontent %}
{% if value == 1 %}
        <h4>Please, Enter Mid-1 Marks Details</h4>
    {% elif value == 2 %}
        <h4>Please, Enter Mid-2 Marks Details</h4>
    {% elif value == 3 %}
        <h4>Please, Enter Sem Marks Details</h4>
    {% else %}
        <h4>Please, Enter Attendance Details</h4>
    {% endif %}<br>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

templates/myMentor/mentorBase.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Mentor-Home
{% endblock %}
{% block head %}
 <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
        <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
        .textarea {
          border: 1px solid #ccc;
          font-family: inherit;
          font-size: inherit;
          padding: 1px 6px;
        }
       .textarea {
          display: block;
          width: 100%;
          overflow: hidden;
          resize: both;
          min-height: 60px;
          line-height: 20px;
           border-radius: 5px;

        }

        .textarea[contenteditable]:empty::before {
          content: "Write a note..";
          color: gray;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            padding: 0 15px;
        }
    </style>

    {% endblock %}
{% block content %}
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-1 shadow">
        {% if user.is_authenticated %}
        <button data-brackets-id="230" class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span data-brackets-id="231" class="navbar-toggler-icon"></span>
        </button>
        {% endif %}
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% if user.is_authenticated %}{% url 'mentorHome' %} {% endif %}">
            College
        </a>
    </header>
    <div class="container">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                  <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% if user.is_authenticated %}{% url 'mentorHome' %} {% endif %}">
                          <span data-feather="home"></span>
                          Home
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'registerStudent' %}">
                          <span data-feather="layers"></span>
                          Register Student
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'StudentMid1' %}">
                          <span data-feather="bar-chart-2"></span>
                          Enter MID-I
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'StudentMid2' %}">
                          <span data-feather="bar-chart-2"></span>
                          Enter MID-II
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'StudentSem1' %}">
                          <span data-feather="bar-chart-2"></span>
                          Enter SEM
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'Attendance' %}">
                          <span data-feather="bar-chart-2"></span>
                          Enter Attendance
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'NotifyStudent' %}">
                          <span data-feather="bar-chart-2"></span>
                          Notify Students
                        </a>
                      </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                          <a class="nav-link" href="{%url 'mentorLogout'%}">Sign out</a>
                        </li>
                        {% endif %}
                    </ul>
                  </div>
                </nav>
                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">MENTOR: {{ user.username }}'s Portal</h1>
                  </div>

                    <div class="container">
                        {% block mentorcontent %}
                        {% endblock %}
                    </div>
                </main>
            </div>
    </div>
{% endblock %}

templates/myMentor/notifystudents.html
{% extends 'myMentor/mentorBase.html' %}
{% load static %}
{% block title %}
    Notify Stuednts
{% endblock %}
{% block mentorcontent %}
<h4>Notify Students</h4>
<br>
<div class="card shadow-lg p-3 mb-5 bg-white rounded">
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="notify" class="form-label">Message</label>
            <input type="text" name="message" class="form-control" id="notify">
          </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<h4>Previous Notifications</h4>
    <div class="row row-cols-2 row-cols-lg-3 g-2 g-lg-2">
        {% for notification in notifications %}
            <div class="card mb-3 shadow-lg bg-white rounded" style="max-width: 18rem; margin-right: 0.8rem;">
                <div class="card-header bg-transparent"><a href="#">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle"       viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                      </svg></a>&nbsp;&nbsp;Date Notified
                      &nbsp;&nbsp;{{ notification.datetime }}
                </div>
                <div class="card-body">
                    <p class="card-text">{{ notification.message }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/myMentor/studentreg.html
{% extends 'myMentor/mentorBase.html' %}
{% load static %}
{% block title %}
    StudentRegistrations @Mentor
{% endblock %}
{% block mentorcontent %}
<h4><strong>Enter Student Details</strong></h4><br>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
        <label for="id_studentid">Studentid</label>
        <input type="text" class="form-control" id="id_studentid" name="studentid" placeholder="Enter studentid" required>
    </div>
        <div class="form-group">
            <label for="id_name">Name</label>
            <input type="text" class="form-control" id="id_name" name="name" placeholder="Enter name" required>
        </div>
        <div class="form-group">
            <label for="id_sem">Sem</label>
            <input type="text" class="form-control" id="id_sem" name="sem" placeholder="Enter sem" required>
        </div>
        <div class="form-group">
            <label for="id_branch">Branch</label>
            <input type="text" class="form-control" id="id_branch" name="branch" placeholder="Enter branch" required>
        </div>
        <div class="form-group">
            <label for="id_batch">Batch</label>
            <input type="text" class="form-control" id="id_batch" name="batch" placeholder="Enter Batch" required>
        </div>
        <div class="form-group">
            <label for="id_regulation">Regulation</label>
            <input type="text" class="form-control" id="id_regulation" name="regulation" placeholder="Enter Regulation" required>
        </div>
        <div class="form-group">
            <label for="id_mentorname">Mentor Name</label>
            <input type="text" class="form-control" id="id_mentorname" name="mentorname" value="{{ mentorname }}" readonly>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}